language: smalltalk

# Select operating system(s)
os:
  - linux

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo32-9.0
  - Pharo32-8.0

#  - Pharo64-alpha
#  - Pharo64-stable
  - Pharo64-9.0
  - Pharo64-8.0
